"""Type stubs for the native extension module."""

__version__: str

def run_cli(args: list[str]) -> int: ...
def lint_store_json(path: str) -> str: ...
def rules_json() -> str: ...
def version() -> str: ...
